# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app_pb2 as app__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GlossaryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWord = channel.unary_unary(
                '/glossary.GlossaryService/CreateWord',
                request_serializer=app__pb2.CreateWordRequest.SerializeToString,
                response_deserializer=app__pb2.WordResponse.FromString,
                _registered_method=True)
        self.GetWord = channel.unary_unary(
                '/glossary.GlossaryService/GetWord',
                request_serializer=app__pb2.GetWordRequest.SerializeToString,
                response_deserializer=app__pb2.WordResponse.FromString,
                _registered_method=True)
        self.DeleteWord = channel.unary_unary(
                '/glossary.GlossaryService/DeleteWord',
                request_serializer=app__pb2.DeleteWordRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateWord = channel.unary_unary(
                '/glossary.GlossaryService/UpdateWord',
                request_serializer=app__pb2.UpdateWordRequest.SerializeToString,
                response_deserializer=app__pb2.WordResponse.FromString,
                _registered_method=True)
        self.ListAllWords = channel.unary_unary(
                '/glossary.GlossaryService/ListAllWords',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=app__pb2.ListResponse.FromString,
                _registered_method=True)


class GlossaryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllWords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlossaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWord': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWord,
                    request_deserializer=app__pb2.CreateWordRequest.FromString,
                    response_serializer=app__pb2.WordResponse.SerializeToString,
            ),
            'GetWord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWord,
                    request_deserializer=app__pb2.GetWordRequest.FromString,
                    response_serializer=app__pb2.WordResponse.SerializeToString,
            ),
            'DeleteWord': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWord,
                    request_deserializer=app__pb2.DeleteWordRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateWord': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWord,
                    request_deserializer=app__pb2.UpdateWordRequest.FromString,
                    response_serializer=app__pb2.WordResponse.SerializeToString,
            ),
            'ListAllWords': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllWords,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=app__pb2.ListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'glossary.GlossaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('glossary.GlossaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GlossaryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/CreateWord',
            app__pb2.CreateWordRequest.SerializeToString,
            app__pb2.WordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/GetWord',
            app__pb2.GetWordRequest.SerializeToString,
            app__pb2.WordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/DeleteWord',
            app__pb2.DeleteWordRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/UpdateWord',
            app__pb2.UpdateWordRequest.SerializeToString,
            app__pb2.WordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/ListAllWords',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            app__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
